"""initial_schema

Revision ID: 0d5070b8e434
Revises: 
Create Date: 2026-04-12 00:56:58.840687
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d5070b8e434'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_tier', sa.String(length=16), nullable=False),
    sa.Column('capability_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agents_enabled', 'agents', ['enabled'], unique=False)
    op.create_index('ix_agents_name', 'agents', ['name'], unique=False)
    op.create_table('magic_links',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_magic_links_email'), 'magic_links', ['email'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_user_created', 'sessions', ['user_id', 'created_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_settings_unique', 'user_settings', ['user_id', 'category', 'key'], unique=True)
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('agent_decision_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_agent_decision_log_agent_created', 'agent_decision_logs', ['agent_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_decision_logs_trace_id'), 'agent_decision_logs', ['trace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_decision', sa.String(length=32), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('briefing_feedback',
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('briefing_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('item_section', sa.String(length=64), nullable=True),
    sa.Column('item_index', sa.Integer(), nullable=True),
    sa.Column('item_title', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ix_bf_user_briefing', 'briefing_feedback', ['user_id', 'briefing_id'], unique=False)
    op.create_index('ix_bf_user_type', 'briefing_feedback', ['user_id', 'feedback_type'], unique=False)
    op.create_index(op.f('ix_briefing_feedback_briefing_id'), 'briefing_feedback', ['briefing_id'], unique=False)
    op.create_table('briefings',
    sa.Column('briefing_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('top_priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes_since_last', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_approvals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('briefing_id')
    )
    op.create_index('ix_briefings_user_date', 'briefings', ['user_id', 'briefing_date'], unique=False)
    op.create_table('browser_actions',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('selector', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('screenshot_before', sa.String(length=64), nullable=True),
    sa.Column('screenshot_after', sa.String(length=64), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('ix_browser_actions_session', 'browser_actions', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_browser_actions_session_id'), 'browser_actions', ['session_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_status', 'conversations', ['user_id', 'status'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index('ix_dlq_operation_status', 'dead_letter_queue', ['operation_type', 'status'], unique=False)
    op.create_index('ix_dlq_user_status', 'dead_letter_queue', ['user_id', 'status'], unique=False)
    op.create_table('engagement_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('signal_source', sa.String(length=64), nullable=False),
    sa.Column('signal_category', sa.String(length=64), nullable=False),
    sa.Column('engaged_count', sa.Integer(), nullable=False),
    sa.Column('dismissed_count', sa.Integer(), nullable=False),
    sa.Column('ignored_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_dismissals', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('last_engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'signal_source', 'signal_category', name='uq_engagement_ws_source_cat')
    )
    op.create_index('ix_engagement_workspace', 'engagement_history', ['workspace_id'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    op.create_index('ix_entities_user_type_name', 'entities', ['user_id', 'entity_type', 'canonical_name'], unique=False)
    op.create_table('integration_audit_events',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=256), nullable=False),
    sa.Column('trust_tier', sa.String(length=4), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('input_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_iaud_workspace', 'integration_audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_iaud_ws_action', 'integration_audit_events', ['workspace_id', 'action'], unique=False)
    op.create_index('ix_iaud_ws_occurred', 'integration_audit_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_index('ix_iaud_ws_server', 'integration_audit_events', ['workspace_id', 'server_name'], unique=False)
    op.create_index('ix_iaud_ws_status', 'integration_audit_events', ['workspace_id', 'status'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('interaction_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('message_preview', sa.String(length=500), nullable=True),
    sa.Column('plan_summary', sa.String(length=500), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('response_preview', sa.String(length=500), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index('ix_interaction_logs_trace', 'interaction_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_interaction_logs_user_id'), 'interaction_logs', ['user_id'], unique=False)
    op.create_index('ix_interaction_logs_ws_user', 'interaction_logs', ['workspace_id', 'user_id', 'created_at'], unique=False)
    op.create_table('mcp_server_catalog',
    sa.Column('catalog_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remote_url', sa.String(length=512), nullable=True),
    sa.Column('default_trust_tier', sa.String(length=4), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('tool_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('catalog_id')
    )
    op.create_index('ix_mcat_workspace', 'mcp_server_catalog', ['workspace_id'], unique=False)
    op.create_index('ix_mcat_ws_name', 'mcp_server_catalog', ['workspace_id', 'server_name'], unique=True)
    op.create_index('ix_mcat_ws_tags', 'mcp_server_catalog', ['workspace_id', 'tags'], unique=False)
    op.create_index('ix_mcat_ws_verified', 'mcp_server_catalog', ['workspace_id', 'verified'], unique=False)
    op.create_table('memories',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('source_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ttl_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('refresh_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('entity_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_memories_last_accessed', 'memories', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index('ix_memories_user_scope', 'memories', ['user_id', 'scope'], unique=False)
    op.create_index('ix_memories_user_type_status', 'memories', ['user_id', 'memory_type', 'status'], unique=False)
    op.create_table('normalized_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_account_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('actor_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_ref', sa.String(length=512), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('causation_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_events_user_occurred', 'normalized_events', ['user_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_user_source_entity', 'normalized_events', ['user_id', 'source', 'entity_id'], unique=False)
    op.create_index(op.f('ix_normalized_events_user_id'), 'normalized_events', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_priority', 'notifications', ['user_id', 'priority_score'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index('ix_oauth_connections_user_provider', 'oauth_connections', ['user_id', 'provider'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index('ix_oauth_tokens_user_provider', 'oauth_tokens', ['user_id', 'provider'], unique=True)
    op.create_table('observation_cursors',
    sa.Column('cursor_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('cursor_type', sa.String(length=32), nullable=False),
    sa.Column('cursor_value', sa.String(length=512), nullable=False),
    sa.Column('last_observation_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cursor_id'),
    sa.UniqueConstraint('user_id', 'source', name='uq_cursor_user_source')
    )
    op.create_index('ix_cursor_user_source', 'observation_cursors', ['user_id', 'source'], unique=False)
    op.create_table('org_allowlists',
    sa.Column('allowlist_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('server_url_pattern', sa.String(length=512), nullable=True),
    sa.Column('max_trust_tier', sa.String(length=4), nullable=False),
    sa.Column('allowed_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocked_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allowlist_id')
    )
    op.create_index('ix_oal_workspace', 'org_allowlists', ['workspace_id'], unique=False)
    op.create_index('ix_oal_ws_enabled', 'org_allowlists', ['workspace_id', 'enabled'], unique=False)
    op.create_index('ix_oal_ws_server', 'org_allowlists', ['workspace_id', 'server_name'], unique=True)
    op.create_table('perception_state',
    sa.Column('state_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), server_default='paused', nullable=False),
    sa.Column('base_interval_s', sa.Integer(), server_default='300', nullable=False),
    sa.Column('effective_interval_s', sa.Integer(), server_default='300', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_interval_s', sa.Integer(), nullable=True),
    sa.Column('watch_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('circuit_state', sa.String(length=16), server_default='closed', nullable=False),
    sa.Column('circuit_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_run', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signal_source', sa.String(length=32), nullable=True),
    sa.Column('signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', 'source', name='uq_pst_ws_user_source')
    )
    op.create_index('ix_pst_next_run', 'perception_state', ['next_run_at'], unique=False)
    op.create_index('ix_pst_user', 'perception_state', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_ref', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.String(length=256), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('required_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('success_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('ix_plans_idempotency_key', 'plans', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('ix_plans_user_created', 'plans', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('runtime_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_revt_occurred', 'runtime_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_index('ix_revt_workspace', 'runtime_events', ['workspace_id'], unique=False)
    op.create_index('ix_revt_ws_run', 'runtime_events', ['workspace_id', 'run_id'], unique=False)
    op.create_index('ix_revt_ws_type', 'runtime_events', ['workspace_id', 'event_type'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('schedule_type', sa.String(length=32), nullable=False),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index('ix_sched_user_next', 'schedules', ['user_id', 'enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('server_trust_records',
    sa.Column('trust_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('server_url', sa.String(length=512), nullable=True),
    sa.Column('trust_tier', sa.String(length=4), nullable=False),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trust_id')
    )
    op.create_index('ix_server_trust_tier', 'server_trust_records', ['workspace_id', 'trust_tier'], unique=False)
    op.create_index('ix_server_trust_workspace', 'server_trust_records', ['workspace_id'], unique=False)
    op.create_index('ix_server_trust_ws_name', 'server_trust_records', ['workspace_id', 'server_name'], unique=True)
    op.create_table('token_usage',
    sa.Column('usage_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('ix_token_usage_agent_created', 'token_usage', ['agent_name', 'created_at'], unique=False)
    op.create_index('ix_token_usage_trace', 'token_usage', ['trace_id'], unique=False)
    op.create_table('tool_definitions',
    sa.Column('tool_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotent', sa.Boolean(), nullable=False),
    sa.Column('connector_type', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=True),
    sa.Column('server', sa.String(length=64), nullable=True),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index('ix_tool_defs_capability', 'tool_definitions', ['workspace_id', 'capability'], unique=False)
    op.create_index('ix_tool_defs_connector', 'tool_definitions', ['connector_type'], unique=False)
    op.create_index('ix_tool_defs_global_name', 'tool_definitions', ['name'], unique=True, postgresql_where='workspace_id IS NULL')
    op.create_index('ix_tool_defs_risk', 'tool_definitions', ['risk_level'], unique=False)
    op.create_index('ix_tool_defs_server', 'tool_definitions', ['workspace_id', 'server'], unique=False)
    op.create_index('ix_tool_defs_ws_name', 'tool_definitions', ['workspace_id', 'name'], unique=True, postgresql_where='workspace_id IS NOT NULL')
    op.create_table('traces',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('total_thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('agents_invoked', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('tools_called', postgresql.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('context_summary', sa.String(length=2000), nullable=True),
    sa.Column('final_result', sa.String(length=2000), nullable=True),
    sa.Column('memory_writes', sa.Integer(), nullable=False),
    sa.Column('approval_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('spans_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index('ix_traces_status', 'traces', ['status'], unique=False)
    op.create_index('ix_traces_trigger', 'traces', ['trigger'], unique=False)
    op.create_index(op.f('ix_traces_user_id'), 'traces', ['user_id'], unique=False)
    op.create_index('ix_traces_user_started', 'traces', ['user_id', 'started_at'], unique=False)
    op.create_table('triggers',
    sa.Column('trigger_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_index('ix_triggers_user_enabled', 'triggers', ['user_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_triggers_user_id'), 'triggers', ['user_id'], unique=False)
    op.create_table('trust_ceilings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=False),
    sa.Column('max_level', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'capability', name='uq_trust_ceiling')
    )
    op.create_table('trust_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('modified_count', sa.Integer(), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('last_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'capability', 'risk_level', name='uq_trust_state')
    )
    op.create_index('ix_trust_state_lookup', 'trust_states', ['workspace_id', 'capability', 'risk_level'], unique=False)
    op.create_table('ui_surfaces',
    sa.Column('surface_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('surface_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('surface_id')
    )
    op.create_index('ix_ui_surfaces_user_type', 'ui_surfaces', ['user_id', 'surface_type'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('subscription_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('callback_url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index('ix_webhook_subs_external', 'webhook_subscriptions', ['external_id'], unique=False)
    op.create_index('ix_webhook_subs_ws', 'webhook_subscriptions', ['workspace_id'], unique=False)
    op.create_index('ix_webhook_subs_ws_provider', 'webhook_subscriptions', ['workspace_id', 'provider'], unique=False)
    op.create_index('ix_webhook_subs_ws_status', 'webhook_subscriptions', ['workspace_id', 'status'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_members_unique', 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aliases_entity', 'entity_aliases', ['entity_id'], unique=False)
    op.create_index('ix_aliases_lookup', 'entity_aliases', ['alias'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('relation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('from_entity_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('to_entity_id', sa.String(length=64), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index(op.f('ix_entity_relationships_user_id'), 'entity_relationships', ['user_id'], unique=False)
    op.create_index('ix_entity_rels_ws', 'entity_relationships', ['workspace_id'], unique=False)
    op.create_index('ix_relations_from', 'entity_relationships', ['from_entity_id', 'relation_type'], unique=False)
    op.create_index('ix_relations_to', 'entity_relationships', ['to_entity_id', 'relation_type'], unique=False)
    op.create_table('integration_installations',
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remote_url', sa.String(length=512), nullable=True),
    sa.Column('trust_id', sa.String(length=64), nullable=True),
    sa.Column('auth_provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('scopes_granted', postgresql.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trust_id'], ['server_trust_records.trust_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('install_id')
    )
    op.create_index('ix_inst_status', 'integration_installations', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_inst_workspace', 'integration_installations', ['workspace_id'], unique=False)
    op.create_index('ix_inst_ws_server', 'integration_installations', ['workspace_id', 'server_name'], unique=True)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('model_calls',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tools_called', postgresql.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('decision', sa.String(length=256), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('ix_model_calls_agent_created', 'model_calls', ['agent_name', 'created_at'], unique=False)
    op.create_index('ix_model_calls_trace', 'model_calls', ['trace_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('task_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=True),
    sa.Column('policy_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('graph_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_id_ref', sa.String(length=64), nullable=True),
    sa.Column('runtime_version', sa.String(length=32), nullable=True),
    sa.Column('planner_version', sa.String(length=32), nullable=True),
    sa.Column('verifier_version', sa.String(length=32), nullable=True),
    sa.Column('context_pack_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_task_runs_idempotency', 'task_runs', ['idempotency_key'], unique=True, postgresql_where=sa.text("idempotency_key IS NOT NULL AND status NOT IN ('completed', 'failed', 'cancelled')"))
    op.create_index('ix_task_runs_source', 'task_runs', ['source', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_runs_task_id_ref'), 'task_runs', ['task_id_ref'], unique=False)
    op.create_index(op.f('ix_task_runs_user_id'), 'task_runs', ['user_id'], unique=False)
    op.create_index('ix_task_runs_user_status', 'task_runs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_task_runs_ws_status', 'task_runs', ['workspace_id', 'status'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_bucket', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_links', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_step_id'), 'artifacts', ['step_id'], unique=False)
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_index('ix_artifacts_user_type', 'artifacts', ['user_id', 'artifact_type'], unique=False)
    op.create_table('task_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index('ix_task_checkpoints_run', 'task_checkpoints', ['run_id', 'created_at'], unique=False)
    op.create_table('task_steps',
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('plan_task_id', sa.String(length=64), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('step_type', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('depends_on', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_refs', postgresql.ARRAY(sa.String(length=512)), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('ix_task_steps_run_status', 'task_steps', ['run_id', 'status'], unique=False)
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('approval_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['task_steps.step_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index('ix_approvals_run_status', 'approvals', ['run_id', 'status'], unique=False)
    op.create_index('ix_approvals_user_status', 'approvals', ['user_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_user_status', table_name='approvals')
    op.drop_index('ix_approvals_run_status', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_task_steps_run_status', table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index('ix_task_checkpoints_run', table_name='task_checkpoints')
    op.drop_table('task_checkpoints')
    op.drop_index('ix_artifacts_user_type', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_step_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_task_runs_ws_status', table_name='task_runs')
    op.drop_index('ix_task_runs_user_status', table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_user_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_task_id_ref'), table_name='task_runs')
    op.drop_index('ix_task_runs_source', table_name='task_runs')
    op.drop_index('ix_task_runs_idempotency', table_name='task_runs', postgresql_where=sa.text("idempotency_key IS NOT NULL AND status NOT IN ('completed', 'failed', 'cancelled')"))
    op.drop_table('task_runs')
    op.drop_table('plan_tasks')
    op.drop_index('ix_model_calls_trace', table_name='model_calls')
    op.drop_index('ix_model_calls_agent_created', table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_inst_ws_server', table_name='integration_installations')
    op.drop_index('ix_inst_workspace', table_name='integration_installations')
    op.drop_index('ix_inst_status', table_name='integration_installations')
    op.drop_table('integration_installations')
    op.drop_index('ix_relations_to', table_name='entity_relationships')
    op.drop_index('ix_relations_from', table_name='entity_relationships')
    op.drop_index('ix_entity_rels_ws', table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_user_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index('ix_aliases_lookup', table_name='entity_aliases')
    op.drop_index('ix_aliases_entity', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_workspace_members_unique', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_webhook_subs_ws_status', table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subs_ws_provider', table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subs_ws', table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subs_external', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index('ix_ui_surfaces_user_type', table_name='ui_surfaces')
    op.drop_table('ui_surfaces')
    op.drop_index('ix_trust_state_lookup', table_name='trust_states')
    op.drop_table('trust_states')
    op.drop_table('trust_ceilings')
    op.drop_index(op.f('ix_triggers_user_id'), table_name='triggers')
    op.drop_index('ix_triggers_user_enabled', table_name='triggers')
    op.drop_table('triggers')
    op.drop_index('ix_traces_user_started', table_name='traces')
    op.drop_index(op.f('ix_traces_user_id'), table_name='traces')
    op.drop_index('ix_traces_trigger', table_name='traces')
    op.drop_index('ix_traces_status', table_name='traces')
    op.drop_table('traces')
    op.drop_index('ix_tool_defs_ws_name', table_name='tool_definitions', postgresql_where='workspace_id IS NOT NULL')
    op.drop_index('ix_tool_defs_server', table_name='tool_definitions')
    op.drop_index('ix_tool_defs_risk', table_name='tool_definitions')
    op.drop_index('ix_tool_defs_global_name', table_name='tool_definitions', postgresql_where='workspace_id IS NULL')
    op.drop_index('ix_tool_defs_connector', table_name='tool_definitions')
    op.drop_index('ix_tool_defs_capability', table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index('ix_token_usage_trace', table_name='token_usage')
    op.drop_index('ix_token_usage_agent_created', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('ix_server_trust_ws_name', table_name='server_trust_records')
    op.drop_index('ix_server_trust_workspace', table_name='server_trust_records')
    op.drop_index('ix_server_trust_tier', table_name='server_trust_records')
    op.drop_table('server_trust_records')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index('ix_sched_user_next', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_revt_ws_type', table_name='runtime_events')
    op.drop_index('ix_revt_ws_run', table_name='runtime_events')
    op.drop_index('ix_revt_workspace', table_name='runtime_events')
    op.drop_index('ix_revt_occurred', table_name='runtime_events')
    op.drop_table('runtime_events')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index('ix_plans_user_created', table_name='plans')
    op.drop_index('ix_plans_idempotency_key', table_name='plans', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('plans')
    op.drop_index('ix_pst_user', table_name='perception_state')
    op.drop_index('ix_pst_next_run', table_name='perception_state')
    op.drop_table('perception_state')
    op.drop_index('ix_oal_ws_server', table_name='org_allowlists')
    op.drop_index('ix_oal_ws_enabled', table_name='org_allowlists')
    op.drop_index('ix_oal_workspace', table_name='org_allowlists')
    op.drop_table('org_allowlists')
    op.drop_index('ix_cursor_user_source', table_name='observation_cursors')
    op.drop_table('observation_cursors')
    op.drop_index('ix_oauth_tokens_user_provider', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index('ix_oauth_connections_user_provider', table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_priority', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_normalized_events_user_id'), table_name='normalized_events')
    op.drop_index('ix_events_user_source_entity', table_name='normalized_events')
    op.drop_index('ix_events_user_occurred', table_name='normalized_events')
    op.drop_table('normalized_events')
    op.drop_index('ix_memories_user_type_status', table_name='memories')
    op.drop_index('ix_memories_user_scope', table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index('ix_memories_last_accessed', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_mcat_ws_verified', table_name='mcp_server_catalog')
    op.drop_index('ix_mcat_ws_tags', table_name='mcp_server_catalog')
    op.drop_index('ix_mcat_ws_name', table_name='mcp_server_catalog')
    op.drop_index('ix_mcat_workspace', table_name='mcp_server_catalog')
    op.drop_table('mcp_server_catalog')
    op.drop_index('ix_interaction_logs_ws_user', table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_user_id'), table_name='interaction_logs')
    op.drop_index('ix_interaction_logs_trace', table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index('ix_iaud_ws_status', table_name='integration_audit_events')
    op.drop_index('ix_iaud_ws_server', table_name='integration_audit_events')
    op.drop_index('ix_iaud_ws_occurred', table_name='integration_audit_events')
    op.drop_index('ix_iaud_ws_action', table_name='integration_audit_events')
    op.drop_index('ix_iaud_workspace', table_name='integration_audit_events')
    op.drop_table('integration_audit_events')
    op.drop_index('ix_entities_user_type_name', table_name='entities')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_engagement_workspace', table_name='engagement_history')
    op.drop_table('engagement_history')
    op.drop_index('ix_dlq_user_status', table_name='dead_letter_queue')
    op.drop_index('ix_dlq_operation_status', table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index('ix_conversations_user_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_browser_actions_session_id'), table_name='browser_actions')
    op.drop_index('ix_browser_actions_session', table_name='browser_actions')
    op.drop_table('browser_actions')
    op.drop_index('ix_briefings_user_date', table_name='briefings')
    op.drop_table('briefings')
    op.drop_index(op.f('ix_briefing_feedback_briefing_id'), table_name='briefing_feedback')
    op.drop_index('ix_bf_user_type', table_name='briefing_feedback')
    op.drop_index('ix_bf_user_briefing', table_name='briefing_feedback')
    op.drop_table('briefing_feedback')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_decision_logs_trace_id'), table_name='agent_decision_logs')
    op.drop_index('ix_agent_decision_log_agent_created', table_name='agent_decision_logs')
    op.drop_table('agent_decision_logs')
    op.drop_table('workspaces')
    op.drop_index('ix_user_settings_unique', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('ix_sessions_user_created', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_magic_links_email'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index('ix_agents_name', table_name='agents')
    op.drop_index('ix_agents_enabled', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
