"""filter rules confirmed by the founder

Revision ID: 2bf09847d9ed
Revises: b4d2e07c9a15
Create Date: 2026-08-23 03:27:26.377525
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "2bf09847d9ed"
down_revision: Union[str, None] = "b4d2e07c9a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter_rules",
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("match_kind", sa.String(length=32), nullable=False),
        sa.Column("match_value", sa.String(length=320), nullable=False),
        sa.Column("created_from_approval_id", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rule_id"),
        sa.UniqueConstraint(
            "workspace_id", "source", "match_kind", "match_value", name="uq_filter_rule_match"
        ),
    )
    op.create_index(
        "ix_filter_rules_workspace_source", "filter_rules", ["workspace_id", "source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_filter_rules_workspace_source", table_name="filter_rules")
    op.drop_table("filter_rules")
    # ### end Alembic commands ###
