"""per-unit dismissals

Revision ID: 4636ed97b50e
Revises: 2bf09847d9ed
Create Date: 2026-08-23 04:53:48.475505
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "4636ed97b50e"
down_revision: Union[str, None] = "2bf09847d9ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_dismissals",
        sa.Column("dismissal_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("frame_key", sa.Text(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dismissal_id"),
        sa.UniqueConstraint(
            "workspace_id", "user_id", "frame_key", name="uq_unit_dismissal_ws_user_frame"
        ),
    )
    op.create_index(
        "ix_unit_dismissals_workspace_user",
        "unit_dismissals",
        ["workspace_id", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unit_dismissals_workspace_user", table_name="unit_dismissals")
    op.drop_table("unit_dismissals")
    # ### end Alembic commands ###
