"""add input_schema and timeout_seconds

Revision ID: 6c0964a4f941
Revises: 046
Create Date: 2026-03-27 01:13:21.955783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c0964a4f941'
down_revision: Union[str, None] = '046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_workspace'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_deps_depends_on'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_deps_task'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_tasks_goal'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_workspace'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_obs_user_source'), table_name='observation_status')
    op.drop_index(op.f('ix_observation_status_workspace'), table_name='observation_status')
    op.drop_table('observation_status')
    op.drop_index(op.f('ix_goals_user_status'), table_name='goals')
    op.drop_index(op.f('ix_goals_workspace'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_user_status'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_workspace'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.alter_column('agent_decision_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_decision_logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_agent_decision_logs_workspace'), table_name='agent_decision_logs')
    op.alter_column('approval_policies', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('approval_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approvals', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_approvals_search_vector'), table_name='approvals', postgresql_using='gin')
    op.drop_index(op.f('ix_approvals_workspace'), table_name='approvals')
    op.drop_index(op.f('ix_artifacts_workspace'), table_name='artifacts')
    op.drop_index(op.f('ix_audit_logs_workspace'), table_name='audit_logs')
    op.drop_index(op.f('ix_bf_briefing_id'), table_name='briefing_feedback')
    op.drop_index(op.f('ix_briefing_feedback_workspace'), table_name='briefing_feedback')
    op.create_index(op.f('ix_briefing_feedback_briefing_id'), 'briefing_feedback', ['briefing_id'], unique=False)
    op.drop_index(op.f('ix_briefings_search_vector'), table_name='briefings', postgresql_using='gin')
    op.drop_index(op.f('ix_briefings_workspace'), table_name='briefings')
    op.drop_index(op.f('ix_browser_actions_workspace'), table_name='browser_actions')
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('conversations', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversations_search_vector'), table_name='conversations', postgresql_using='gin')
    op.drop_index(op.f('ix_conversations_workspace'), table_name='conversations')
    op.alter_column('dead_letter_queue', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('dead_letter_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('dead_letter_queue', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_dead_letter_queue_workspace'), table_name='dead_letter_queue')
    op.drop_index(op.f('ix_entities_search_vector'), table_name='entities', postgresql_using='gin')
    op.drop_index(op.f('ix_entities_workspace'), table_name='entities')
    op.alter_column('entity_aliases', 'alias_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'name'::character varying"))
    op.drop_index(op.f('ix_entity_aliases_workspace'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_relationships_workspace'), table_name='entity_relationships')
    op.alter_column('memories', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('memories', 'stability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('memories', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_memories_entity_ids'), table_name='memories', postgresql_using='gin')
    op.drop_index(op.f('ix_memories_search_vector'), table_name='memories', postgresql_using='gin')
    op.drop_index(op.f('ix_memories_workspace'), table_name='memories')
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_search_vector'), table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('ix_messages_workspace'), table_name='messages')
    op.alter_column('model_calls', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cache_creation_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cache_read_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('model_calls', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_model_calls_workspace'), table_name='model_calls')
    op.alter_column('normalized_events', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_normalized_events_search_vector'), table_name='normalized_events', postgresql_using='gin')
    op.drop_index(op.f('ix_normalized_events_workspace'), table_name='normalized_events')
    op.drop_index(op.f('ix_notifications_workspace'), table_name='notifications')
    op.drop_index(op.f('ix_oauth_connections_workspace'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_tokens_workspace'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_observation_cursors_workspace'), table_name='observation_cursors')
    op.alter_column('plan_tasks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_plan_tasks_workspace'), table_name='plan_tasks')
    op.alter_column('plans', 'priority',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('plans', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('plans', 'execution_mode',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'approval_required'::character varying"))
    op.alter_column('plans', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.drop_index(op.f('ix_plans_workspace'), table_name='plans')
    op.drop_index(op.f('ix_procedures_workspace'), table_name='procedures')
    op.drop_index(op.f('ix_schedules_workspace'), table_name='schedules')
    op.drop_index(op.f('ix_task_checkpoints_workspace'), table_name='task_checkpoints')
    op.add_column('task_runs', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_task_runs_workspace'), table_name='task_runs')
    op.create_index(op.f('ix_task_runs_user_id'), 'task_runs', ['user_id'], unique=False)
    op.add_column('task_steps', sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_task_steps_workspace'), table_name='task_steps')
    op.drop_index(op.f('ix_token_usage_workspace'), table_name='token_usage')
    op.drop_index(op.f('ix_tool_definitions_workspace'), table_name='tool_definitions')
    op.alter_column('traces', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('traces', 'total_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cache_creation_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cache_read_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('traces', 'span_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'memory_writes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_traces_workspace'), table_name='traces')
    op.create_index(op.f('ix_traces_user_id'), 'traces', ['user_id'], unique=False)
    op.drop_index(op.f('ix_triggers_workspace'), table_name='triggers')
    op.create_index(op.f('ix_triggers_user_id'), 'triggers', ['user_id'], unique=False)
    op.drop_index(op.f('ix_trust_scores_workspace'), table_name='trust_scores')
    op.drop_index(op.f('ix_ui_surfaces_workspace'), table_name='ui_surfaces')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('webhook_subscriptions', 'delivery_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_subscriptions', 'consecutive_failures',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhook_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_working_memory_workspace'), table_name='working_memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_working_memory_workspace'), 'working_memory', ['workspace_id'], unique=False)
    op.alter_column('webhook_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhook_subscriptions', 'consecutive_failures',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_subscriptions', 'delivery_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ui_surfaces_workspace'), 'ui_surfaces', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_trust_scores_workspace'), 'trust_scores', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_triggers_user_id'), table_name='triggers')
    op.create_index(op.f('ix_triggers_workspace'), 'triggers', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_traces_user_id'), table_name='traces')
    op.create_index(op.f('ix_traces_workspace'), 'traces', ['workspace_id'], unique=False)
    op.alter_column('traces', 'memory_writes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'span_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('traces', 'total_thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cache_read_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_cache_creation_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'total_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.create_index(op.f('ix_tool_definitions_workspace'), 'tool_definitions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_token_usage_workspace'), 'token_usage', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_task_steps_workspace'), 'task_steps', ['workspace_id'], unique=False)
    op.drop_column('task_steps', 'input_schema')
    op.drop_index(op.f('ix_task_runs_user_id'), table_name='task_runs')
    op.create_index(op.f('ix_task_runs_workspace'), 'task_runs', ['workspace_id'], unique=False)
    op.drop_column('task_runs', 'timeout_seconds')
    op.create_index(op.f('ix_task_checkpoints_workspace'), 'task_checkpoints', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_schedules_workspace'), 'schedules', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_procedures_workspace'), 'procedures', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_plans_workspace'), 'plans', ['workspace_id'], unique=False)
    op.alter_column('plans', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('plans', 'execution_mode',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'approval_required'::character varying"))
    op.alter_column('plans', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('plans', 'priority',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_index(op.f('ix_plan_tasks_workspace'), 'plan_tasks', ['workspace_id'], unique=False)
    op.alter_column('plan_tasks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_observation_cursors_workspace'), 'observation_cursors', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_workspace'), 'oauth_tokens', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_oauth_connections_workspace'), 'oauth_connections', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace'), 'notifications', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_normalized_events_workspace'), 'normalized_events', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_normalized_events_search_vector'), 'normalized_events', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('normalized_events', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_model_calls_workspace'), 'model_calls', ['workspace_id'], unique=False)
    op.alter_column('model_calls', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('model_calls', 'thinking_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cache_read_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'cache_creation_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('model_calls', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_messages_workspace'), 'messages', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_messages_search_vector'), 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_memories_workspace'), 'memories', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_memories_search_vector'), 'memories', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_memories_entity_ids'), 'memories', ['entity_ids'], unique=False, postgresql_using='gin')
    op.alter_column('memories', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('memories', 'stability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('memories', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.create_index(op.f('ix_entity_relationships_workspace'), 'entity_relationships', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_workspace'), 'entity_aliases', ['workspace_id'], unique=False)
    op.alter_column('entity_aliases', 'alias_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'name'::character varying"))
    op.create_index(op.f('ix_entities_workspace'), 'entities', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_entities_search_vector'), 'entities', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_dead_letter_queue_workspace'), 'dead_letter_queue', ['workspace_id'], unique=False)
    op.alter_column('dead_letter_queue', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('dead_letter_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('dead_letter_queue', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_conversations_workspace'), 'conversations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_conversations_search_vector'), 'conversations', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('conversations', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_browser_actions_workspace'), 'browser_actions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_briefings_workspace'), 'briefings', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_briefings_search_vector'), 'briefings', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_briefing_feedback_briefing_id'), table_name='briefing_feedback')
    op.create_index(op.f('ix_briefing_feedback_workspace'), 'briefing_feedback', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_bf_briefing_id'), 'briefing_feedback', ['briefing_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_artifacts_workspace'), 'artifacts', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_approvals_workspace'), 'approvals', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_approvals_search_vector'), 'approvals', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('approvals', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('approval_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_policies', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_agent_decision_logs_workspace'), 'agent_decision_logs', ['workspace_id'], unique=False)
    op.alter_column('agent_decision_logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_decision_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('browser_sessions',
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'idle'::character varying"), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('screenshot_artifact_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_action_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('browser_sessions_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('browser_sessions_pkey'))
    )
    op.create_index(op.f('ix_browser_sessions_workspace'), 'browser_sessions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_status'), 'browser_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('goal_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('related_entity_ids', postgresql.ARRAY(sa.VARCHAR(length=64)), autoincrement=False, nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=16), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('success_criteria_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('goals_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', name=op.f('goals_pkey'))
    )
    op.create_index(op.f('ix_goals_workspace'), 'goals', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_goals_user_status'), 'goals', ['user_id', 'status'], unique=False)
    op.create_table('observation_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('last_observed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('items_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_ingested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('observation_status_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('observation_status_pkey'))
    )
    op.create_index(op.f('ix_observation_status_workspace'), 'observation_status', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_obs_user_source'), 'observation_status', ['user_id', 'source'], unique=True)
    op.create_table('tasks',
    sa.Column('task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('parent_task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=64), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=16), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'created'::character varying"), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assigned_agent', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], name=op.f('tasks_goal_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.task_id'], name=op.f('tasks_parent_task_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('tasks_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_workspace'), 'tasks', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_status'), 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_parent'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_goal'), 'tasks', ['goal_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('depends_on_task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('dependency_type', sa.VARCHAR(length=16), server_default=sa.text("'blocks'::character varying"), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.task_id'], name=op.f('task_dependencies_depends_on_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('task_dependencies_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('task_dependencies_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_dependencies_pkey'))
    )
    op.create_index(op.f('ix_task_deps_task'), 'task_dependencies', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_deps_depends_on'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_workspace'), 'task_dependencies', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
