"""add plan_output_json to plans

Revision ID: 933bd5844f8e
Revises: 0d5070b8e434
Create Date: 2026-04-12 05:35:55.933302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '933bd5844f8e'
down_revision: Union[str, None] = '0d5070b8e434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('plan_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'plan_output_json')
    # ### end Alembic commands ###
