"""runtime_events.seq monotonic ordering column

Revision ID: a5f1c2d3e4b6
Revises: c4f9e2a71b83
Create Date: 2026-07-06 00:00:00.000000

Server-assigned BIGINT identity giving a total order across concurrently-writing
workers (occurred_at ties within a txn and skews across workers). Additive:
ADD COLUMN GENERATED BY DEFAULT AS IDENTITY backfills every existing row atomically
(spiked live on the populated table). Makes reconcile-from-event-log possible
(spec §4.8 / §6 Step 5). Index also declared on the ORM model so `alembic check`
stays clean.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "a5f1c2d3e4b6"
down_revision: Union[str, None] = "c4f9e2a71b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "runtime_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
    )
    op.create_index("ix_revt_ws_seq", "runtime_events", ["workspace_id", "seq"])


def downgrade() -> None:
    op.drop_index("ix_revt_ws_seq", table_name="runtime_events")
    op.drop_column("runtime_events", "seq")
