"""add timeout_seconds to task_steps

Revision ID: d9ad551a4b6b
Revises: 933bd5844f8e
Create Date: 2026-04-12 11:50:53.129347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9ad551a4b6b'
down_revision: Union[str, None] = '933bd5844f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_steps', 'timeout_seconds')
    # ### end Alembic commands ###
