"""widen external-id columns to Text (calendar ids exceed varchar 128/256)

Revision ID: da007259d93c
Revises: 1a2770a28c39
Create Date: 2026-07-21 00:26:33.825446
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'da007259d93c'
down_revision: Union[str, None] = '1a2770a28c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dead_letter_queue', 'source_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('normalized_events', 'entity_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('normalized_events', 'idempotency_key',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_events', 'idempotency_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('normalized_events', 'entity_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('dead_letter_queue', 'source_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
